# -*- coding: utf-8 -*-
"""NLP_UPDATE_2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7Uv8wwycp0s7Lzk03UXvKg8v61DjMcF

# =====================================================
# BAGUS NOTEBOOK 2026
# Text Classification with Modern Embeddings
# Author : Bagustyo
# =====================================================

# Mengapa Notebook Ini Ada?

Pada tahun 2023 kita mengubah text menjadi angka
menggunakan tokenization dan embedding sederhana.

Pada tahun 2026 kita memanfaatkan embedding model
yang sudah memahami makna kalimat.

Target:

Text
↓
Embedding
↓
Classifier
↓
Prediction
↓
API
"""

!pip install sentence-transformers
!pip install lightgbm
!pip install scikit-learn
!pip install fastapi uvicorn

"""## Filosofi

Jangan install library karena tutorial menyuruh.

Install karena kita tahu perannya.

sentence-transformers
→ memahami kalimat

lightgbm
→ classifier

fastapi
→ deployment
"""

import pandas as pd

df = pd.read_excel("/content/drive/MyDrive/TYO_NLTK/DATASET_3000/DATASET_JUDUL_BERITA.xlsx")

df = df[['JUDUL','KATEGORI']]
df.head(10)

df['KATEGORI'].value_counts()

"""Sebelum melatih model,
lihat dulu isi data.

Ini seperti dokter memeriksa pasien
sebelum memberikan obat.
"""

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(
    df["KATEGORI"]
)

"""Mesin tidak memahami:

ekonomi
olahraga
kesehatan

Mesin memahami:

0
1
2
"""

y

from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(
    "intfloat/multilingual-e5-small"
)

"""Dulu:

Motor rusak

dan

Sepeda motor mengalami kerusakan

dianggap berbeda.

Sekarang embedding modern memahami
bahwa kedua kalimat memiliki makna yang dekat.
"""

X = embedding_model.encode(
    df["JUDUL"].tolist(),
    normalize_embeddings=True
)

"""Kita lihat hasil embedd nya :D"""

X[:10]

"""Kita Visualiasasi dulu"""

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

pca = PCA(n_components=2)

X_2d = pca.fit_transform(X)

"""Pertanyaan:

Apakah artikel olahraga
berkumpul dengan olahraga?

Apakah artikel ekonomi
berkumpul dengan ekonomi?

Mari lihat.
"""

plt.scatter(
    X_2d[:,0],
    X_2d[:,1],
    c=y
)

X_2d = pca.fit_transform(X)

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    stratify=y,
    random_state=42
)

"""Pisahkan data latihan dan ujian.

Jika tidak,
model akan menghafal.
"""

from lightgbm import LGBMClassifier

clf = LGBMClassifier(
    n_estimators=300,
    learning_rate=0.05
)

"""Mengapa LightGBM?

Karena:

- cepat
- ringan
- akurat
- cocok untuk embedding
"""

clf.fit(
    X_train,
    y_train
)

"""Saat ini Mesin sedang belajar.

Bukan belajar bahasa Indoneisa dong

Tetapi belajar pola heheeheh
"""

pred = clf.predict(X_test)

from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        pred
    )
)

"""## Mengapa Tidak Cukup Melihat Accuracy?

Accuracy hanya menjawab satu pertanyaan:

> "Berapa persen prediksi yang benar?"

Misalnya model menghasilkan:

```python
Accuracy = 95%
```

Angka tersebut terlihat sangat bagus, tetapi belum memberi tahu kita:

- kelas mana yang paling sering salah
- apakah model sering melewatkan suatu kategori
- apakah model terlalu sering menebak kategori tertentu

---

### Precision

Precision menjawab pertanyaan:

> "Ketika model mengatakan sebuah berita termasuk kategori tertentu, seberapa sering prediksi itu benar?"

Contoh:

Model memprediksi 120 berita sebagai **POLITIK**.

Dari 120 berita tersebut:

- 80 benar-benar POLITIK ✅
- 40 sebenarnya bukan POLITIK ❌

Maka:

```text
Precision = 80 / 120
          = 66.7%
```

Artinya:

> Dari semua berita yang diprediksi sebagai POLITIK, hanya 66.7% yang benar.

---

### Recall

Recall menjawab pertanyaan:

> "Dari seluruh berita POLITIK yang benar-benar ada, berapa banyak yang berhasil ditemukan model?"

Contoh:

Terdapat 100 berita POLITIK dalam dataset.

Model berhasil menemukan:

- 80 berita POLITIK ✅
- 20 berita POLITIK terlewat ❌

Maka:

```text
Recall = 80 / 100
       = 80%
```

Artinya:

> Model berhasil menemukan 80% berita POLITIK yang sebenarnya ada.

---

### F1 Score

F1 Score merupakan keseimbangan antara Precision dan Recall.

Jika:

- Precision tinggi tetapi Recall rendah
- atau Recall tinggi tetapi Precision rendah

maka nilai F1 akan turun.

F1 cocok digunakan ketika kita ingin melihat kualitas model secara keseluruhan.

---

### Pada Dataset Berita

Misalnya hasil evaluasi:

```text
              precision    recall    f1-score

EKONOMI          0.97       0.95       0.96
KESEHATAN        0.98       0.99       0.98
OLAH RAGA        0.96       0.97       0.96
POLITIK          0.92       0.95       0.93

accuracy                               0.96
```

Dari accuracy saja kita hanya tahu:

```text
Model benar 96%
```

Tetapi dari precision, recall, dan f1-score kita bisa mengetahui bahwa:

- Kategori POLITIK paling sulit diprediksi
- Model sering tertukar antara POLITIK dan kategori lain
- Ada peluang memperbaiki performa khusus pada kategori POLITIK

---

### Kesimpulan

Accuracy memberi tahu:

> "Seberapa sering model benar?"

Precision memberi tahu:

> "Jika model yakin suatu kategori, apakah ia benar?"

Recall memberi tahu:

> "Apakah ada data yang terlewat?"

F1 Score memberi tahu:

> "Seberapa baik keseimbangan antara Precision dan Recall?"

Karena itu, pada proyek NLP modern kita hampir selalu melihat:

- Accuracy
- Precision
- Recall
- F1 Score
- Confusion Matrix

bukan Accuracy saja.
"""

from sklearn.metrics import ConfusionMatrixDisplay

ConfusionMatrixDisplay.from_predictions(
    y_test,
    pred
)

"""Kesalahan model lebih penting
daripada keberhasilan model.

Karena dari situlah kita belajar.

# Pertanyaan Penting

Mengapa model salah?

Apakah label salah?

Apakah artikel ambigu?

Apakah kategori tumpang tindih?

Machine Learning bukan hanya coding.

Machine Learning adalah investigasi.
"""

import joblib

joblib.dump(
    clf,
    "/content/drive/MyDrive/TYO_NLTK/MODEL/2026/classifier.pkl"
)

joblib.dump(
    encoder,
    "/content/drive/MyDrive/TYO_NLTK/MODEL/2026/label_encoder.pkl"
)

"""# ==========================================
# TESTING PREDICTION
# ==========================================
"""

samples = [
    "Bank Indonesia menaikkan suku bunga acuan menjadi 6 persen",
    "Timnas Indonesia berhasil mengalahkan Jepang dengan skor 2-1",
    "Kementerian Kesehatan melaporkan peningkatan kasus DBD",
    "Presiden bertemu dengan pimpinan partai koalisi"
]

for text in samples:

    embedding = embedding_model.encode(
        [text],
        normalize_embeddings=True
    )

    prediction = clf.predict(embedding)

    label = encoder.inverse_transform(
        prediction
    )[0]

    print("=" * 60)
    print(f"Judul : {text}")
    print(f"Prediksi : {label}")

"""# KLO MAU LOAD MODEL"""

import joblib
from sentence_transformers import SentenceTransformer


clf = joblib.load(
    "/content/drive/MyDrive/TYO_NLTK/MODEL/2026/classifier.pkl"
)

encoder = joblib.load(
    "/content/drive/MyDrive/TYO_NLTK/MODEL/2026/label_encoder.pkl"
)


embedding_model = SentenceTransformer(
    "intfloat/multilingual-e5-small"
)

def predict_news(text):

    embedding = embedding_model.encode(
        [text],
        normalize_embeddings=True
    )

    pred = clf.predict(embedding)

    label = encoder.inverse_transform(
        pred
    )[0]

    confidence = clf.predict_proba(
        embedding
    ).max()

    return {
        "label": label,
        "confidence": float(confidence)
    }

predict_news(
    "Bank Indonesia menaikkan suku bunga acuan menjadi 6 persen"

)